class GRoleStatusModel {
    static fields = [
     
        { name: 'version', method: 'readUByte' },
        { name: 'level', method: 'readInt32' },
        { name: 'level2', method: 'readInt32' },
        { name: 'exp', method: 'readInt32' },
        { name: 'sp', method: 'readInt32' },
        { name: 'pts', method: 'readInt32' },
        { name: 'hp', method: 'readInt32' },
        { name: 'mp', method: 'readInt32' },
        { name: 'posx', method: 'readFloatBE' },
        { name: 'posy', method: 'readFloatBE' },
        { name: 'posz', method: 'readFloatBE' },
        { name: 'worldtag', method: 'readInt32' },
        { name: 'invader_state', method: 'readInt32' },
        { name: 'invader_time', method: 'readInt32' },
        { name: 'pariah_time', method: 'readInt32' },
        { name: 'reputation', method: 'readInt32' },
        { name: 'custom_status', method: 'readOctets' },
        { name: 'filter_data', method: 'readOctets' },
        { name: 'charactermode', method: 'readOctets' },
        { name: 'instancekeylist', method: 'readOctets' },
        { name: 'dbltime_expire', method: 'readInt32' },
        { name: 'dbltime_mode', method: 'readInt32' },
        { name: 'dbltime_begin', method: 'readInt32' },
        { name: 'dbltime_used', method: 'readInt32' },
        { name: 'dbltime_max', method: 'readInt32' },
        { name: 'time_used', method: 'readInt32' },
        { name: 'dbltime_data', method: 'readOctets' },
        { name: 'storesize', method: 'readUInt16LE' },
        { name: 'petcorral', method: 'readOctets' },
        { name: 'property', method: 'readOctets' },
        { name: 'var_data', method: 'readOctets' },
        { name: 'skills', method: 'readOctets' },
        { name: 'storehousepasswd', method: 'readOctets' },
        { name: 'waypointlist', method: 'readOctets' },
        { name: 'coolingtime', method: 'readOctets' },
        { name: 'npc_relation', method: 'readOctets' },
        { name: 'multi_exp_ctrl', method: 'readOctets' },
        { name: 'storage_task', method: 'readOctets' },
        { name: 'faction_contrib', method: 'readOctets' },
        { name: 'force_data', method: 'readOctets' },
        { name: 'online_award', method: 'readOctets' },
        { name: 'profit_time_data', method: 'readOctets' },
        { name: 'country_data', method: 'readOctets' },
        { name: 'king_data', method: 'readOctets' },
        { name: 'meridian_data', method: 'readOctets' },
        { name: 'extraprop', method: 'readOctets' },
        { name: 'title_data', method: 'readOctets' },
        { name: 'reincarnation_data', method: 'readOctets' },
        { name: 'realm_data', method: 'readOctets' },
    ];
}

module.exports = GRoleStatusModel;
